#!/usr/bin/env bash
# setup-env.sh — Generate .env from a secrets manager
#
# This is a template showing how to populate .env from a CLI-based
# secrets manager (e.g., Bitwarden CLI, 1Password CLI, Vault, etc.).
#
# Adapt the secret retrieval commands to your own tooling.
#
# Usage:
#   chmod +x setup-env.sh
#   ./setup-env.sh

set -euo pipefail

ENV_FILE=".env"

# ── Helper: replace with your secrets manager CLI ────────────────────
# Examples:
#   rbw get "entry-name"          # Bitwarden (rbw)
#   op read "op://vault/item"     # 1Password CLI
#   vault kv get secret/aiwn      # HashiCorp Vault
get_secret() {
    local name="$1"
    echo "CHANGE_ME_${name}"
}

echo "Generating ${ENV_FILE}..."

cat > "${ENV_FILE}" << EOF
# ── SloppyRoad Environment Configuration ──
# Generated by setup-env.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT commit this file to version control.

# ── Auth / JWT ────────────────────────────────────────────────────────
AIWN_JWT_SECRET_KEY=$(get_secret "jwt-secret")

# ── Database ──────────────────────────────────────────────────────────
AIWN_DB_PASSWORD=$(get_secret "db-password")

# ── LLM API Key ──────────────────────────────────────────────────────
AIWN_LITELLM_API_KEY=$(get_secret "litellm-api-key")

# ── Image Generation ─────────────────────────────────────────────────
# AIWN_REPLICATE_API_TOKEN=$(get_secret "replicate-api-token")

# ── BYOK Encryption ──────────────────────────────────────────────────
# AIWN_ENCRYPTION_KEY=$(get_secret "encryption-key")

# ── Stripe ────────────────────────────────────────────────────────────
# AIWN_STRIPE_API_KEY=$(get_secret "stripe-api-key")
# AIWN_STRIPE_WEBHOOK_SECRET=$(get_secret "stripe-webhook-secret")

# ── App Settings ──────────────────────────────────────────────────────
AIWN_DEBUG=false
AIWN_LOG_LEVEL=INFO
AIWN_APP_PORT=8003
EOF

echo "Done. ${ENV_FILE} written with placeholder secrets."
echo "Edit the get_secret() function to use your secrets manager, then re-run."
