"""sync schema additions: chapter_images, novel_seeds tables + new columns

Revision ID: 8fcaebd46945
Revises: 651e2b594027
Create Date: 2026-03-14 01:42:13.781805+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fcaebd46945'
down_revision: Union[str, None] = '651e2b594027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('novel_seeds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('seed_id', sa.String(length=100), nullable=False),
    sa.Column('seed_category', sa.String(length=50), nullable=False),
    sa.Column('seed_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('novel_id', 'seed_id', name='uq_novel_seed')
    )
    op.create_table('chapter_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('art_asset_id', sa.Integer(), nullable=True),
    sa.Column('paragraph_index', sa.Integer(), nullable=False),
    sa.Column('scene_description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['art_asset_id'], ['art_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chapter_images_chapter', 'chapter_images', ['chapter_id'], unique=False)
    op.add_column('characters', sa.Column('visual_appearance', sa.Text(), nullable=True))
    op.add_column('factions', sa.Column('visual_description', sa.Text(), nullable=True))
    op.add_column('novel_tags', sa.Column('tag_category', sa.String(length=50), nullable=True))
    op.add_column('novels', sa.Column('image_budget_cents', sa.Integer(), nullable=False))
    op.add_column('novels', sa.Column('image_spent_cents', sa.Integer(), nullable=False))
    op.add_column('novels', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('regions', sa.Column('visual_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regions', 'visual_description')
    op.drop_column('novels', 'description')
    op.drop_column('novels', 'image_spent_cents')
    op.drop_column('novels', 'image_budget_cents')
    op.drop_column('novel_tags', 'tag_category')
    op.drop_column('factions', 'visual_description')
    op.drop_column('characters', 'visual_appearance')
    op.drop_index('idx_chapter_images_chapter', table_name='chapter_images')
    op.drop_table('chapter_images')
    op.drop_table('novel_seeds')
    # ### end Alembic commands ###
