"""initial schema

Revision ID: 651e2b594027
Revises: 
Create Date: 2026-03-11 05:31:09.049137+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '651e2b594027'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('auth_provider', sa.String(length=20), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('cookie_token', sa.String(length=64), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cookie_token'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_cookie_token', 'users', ['cookie_token'], unique=False, postgresql_where='cookie_token IS NOT NULL')
    op.create_index('idx_users_email', 'users', ['email'], unique=False, postgresql_where='email IS NOT NULL')
    op.create_table('author_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('api_budget_cents', sa.Integer(), nullable=False),
    sa.Column('api_spent_cents', sa.Integer(), nullable=False),
    sa.Column('image_budget_cents', sa.Integer(), nullable=False),
    sa.Column('image_spent_cents', sa.Integer(), nullable=False),
    sa.Column('default_model', sa.String(length=100), nullable=True),
    sa.Column('plan_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('novels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('genre', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('autonomous_enabled', sa.Boolean(), nullable=False),
    sa.Column('autonomous_cadence_hours', sa.Integer(), nullable=False),
    sa.Column('autonomous_daily_budget_cents', sa.Integer(), nullable=False),
    sa.Column('autonomous_skip_arc_boundaries', sa.Boolean(), nullable=False),
    sa.Column('completion_summary', sa.Text(), nullable=True),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_index('idx_novels_author', 'novels', ['author_id'], unique=False)
    op.create_table('reader_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('reading_preferences', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('arc_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('arc_number', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('planned_chapters', sa.Integer(), nullable=True),
    sa.Column('target_chapter_start', sa.Integer(), nullable=True),
    sa.Column('target_chapter_end', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('author_notes', sa.Text(), nullable=True),
    sa.Column('themes', sa.JSON(), nullable=True),
    sa.Column('key_events', sa.JSON(), nullable=True),
    sa.Column('character_arcs', sa.JSON(), nullable=True),
    sa.Column('is_final_arc', sa.Boolean(), nullable=False),
    sa.Column('resolution_targets', sa.JSON(), nullable=True),
    sa.Column('system_revision_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_arc_plans_novel_status', 'arc_plans', ['novel_id', 'status'], unique=False)
    op.create_table('art_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('prompt_used', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('thumbnail_path', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('parent_asset_id', sa.Integer(), nullable=True),
    sa.Column('seed_value', sa.Integer(), nullable=True),
    sa.Column('generation_params', sa.JSON(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('chapter_context', sa.Integer(), nullable=True),
    sa.Column('style_tags', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_asset_id'], ['art_assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('art_style_guides',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('style_description', sa.Text(), nullable=False),
    sa.Column('style_name', sa.String(length=100), nullable=True),
    sa.Column('color_palette', sa.JSON(), nullable=True),
    sa.Column('art_direction', sa.Text(), nullable=True),
    sa.Column('base_prompt_prefix', sa.Text(), nullable=True),
    sa.Column('base_negative_prompt', sa.Text(), nullable=True),
    sa.Column('reference_asset_ids', sa.JSON(), nullable=True),
    sa.Column('model_preference', sa.String(length=100), nullable=True),
    sa.Column('default_params', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('novel_id', 'style_name', name='uq_style_guide_novel_name')
    )
    op.create_table('butterfly_choices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('choice_text_a', sa.Text(), nullable=False),
    sa.Column('choice_text_b', sa.Text(), nullable=False),
    sa.Column('choice_description', sa.Text(), nullable=True),
    sa.Column('option_a_theme', sa.String(length=100), nullable=True),
    sa.Column('option_b_theme', sa.String(length=100), nullable=True),
    sa.Column('result', sa.String(length=1), nullable=True),
    sa.Column('vote_count_a', sa.Integer(), nullable=False),
    sa.Column('vote_count_b', sa.Integer(), nullable=False),
    sa.Column('narrative_impact', sa.Text(), nullable=True),
    sa.Column('personality_modifier', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('closes_at', sa.DateTime(), nullable=True),
    sa.Column('voting_closes_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('context_retrieval_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('retrieved_entry_ids', sa.JSON(), nullable=False),
    sa.Column('relevance_scores', sa.JSON(), nullable=True),
    sa.Column('total_token_estimate', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cosmology',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('fundamental_forces', sa.JSON(), nullable=False),
    sa.Column('planes_of_existence', sa.JSON(), nullable=False),
    sa.Column('creation_myth', sa.Text(), nullable=True),
    sa.Column('cosmic_laws', sa.JSON(), nullable=True),
    sa.Column('energy_types', sa.JSON(), nullable=False),
    sa.Column('reality_tiers', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('novel_id')
    )
    op.create_table('foreshadowing_seeds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('planted_at_chapter', sa.Integer(), nullable=False),
    sa.Column('target_chapter_range', sa.JSON(), nullable=True),
    sa.Column('seed_type', sa.String(length=30), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('fulfilled_at_chapter', sa.Integer(), nullable=True),
    sa.Column('scope_tier', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generation_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('arq_job_id', sa.String(length=100), nullable=True),
    sa.Column('chapter_number', sa.Integer(), nullable=True),
    sa.Column('stage_name', sa.String(length=50), nullable=True),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('partial_data_cleaned', sa.Boolean(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('arq_job_id')
    )
    op.create_index('idx_generation_jobs_novel', 'generation_jobs', ['novel_id'], unique=False)
    op.create_index('idx_generation_jobs_status', 'generation_jobs', ['status'], unique=False)
    op.create_table('llm_usage_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_cents', sa.Float(), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_llm_usage_created', 'llm_usage_log', ['created_at'], unique=False)
    op.create_index('idx_llm_usage_novel', 'llm_usage_log', ['novel_id'], unique=False)
    op.create_index('idx_llm_usage_user', 'llm_usage_log', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=True),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('action_url', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('delivery_channel', sa.String(length=20), nullable=False),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_user_unread', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    op.create_table('novel_access',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('access_type', sa.String(length=20), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('novel_id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_table('novel_ratings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('reader_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reader_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('novel_id', 'reader_id', name='uq_novel_rating')
    )
    op.create_table('novel_settings',
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('planning_mode', sa.String(length=20), nullable=False),
    sa.Column('pov_mode', sa.String(length=20), nullable=False),
    sa.Column('content_rating', sa.String(length=20), nullable=False),
    sa.Column('target_chapter_length', sa.Integer(), nullable=False),
    sa.Column('target_chapter_length_min', sa.Integer(), nullable=False),
    sa.Column('target_chapter_length_max', sa.Integer(), nullable=False),
    sa.Column('default_temperature', sa.Float(), nullable=False),
    sa.Column('generation_model', sa.String(length=100), nullable=True),
    sa.Column('analysis_model', sa.String(length=100), nullable=True),
    sa.Column('reader_influence_enabled', sa.Boolean(), nullable=False),
    sa.Column('image_generation_enabled', sa.Boolean(), nullable=False),
    sa.Column('art_style_preset', sa.String(length=100), nullable=True),
    sa.Column('custom_genre_conventions', sa.Text(), nullable=True),
    sa.Column('max_scope_tiers', sa.Integer(), nullable=True),
    sa.Column('autonomous_generation_enabled', sa.Boolean(), nullable=False),
    sa.Column('autonomous_cadence_hours', sa.Integer(), nullable=False),
    sa.Column('autonomous_skip_arc_boundaries', sa.Boolean(), nullable=False),
    sa.Column('autonomous_daily_budget_cents', sa.Integer(), nullable=False),
    sa.Column('last_autonomous_generation_at', sa.DateTime(), nullable=True),
    sa.Column('autonomous_consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('novel_id')
    )
    op.create_table('novel_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('total_chapters', sa.Integer(), nullable=False),
    sa.Column('total_words', sa.Integer(), nullable=False),
    sa.Column('total_readers', sa.Integer(), nullable=False),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('last_chapter_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('novel_id')
    )
    op.create_table('novel_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(length=100), nullable=False),
    sa.Column('is_system_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('novel_id', 'tag_name', name='uq_novel_tag')
    )
    op.create_table('oracle_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('reader_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('answer_chapter', sa.Integer(), nullable=True),
    sa.Column('asked_at_chapter', sa.Integer(), nullable=True),
    sa.Column('votes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('revelation_target_type', sa.String(length=50), nullable=True),
    sa.Column('revelation_target_id', sa.Integer(), nullable=True),
    sa.Column('revelation_planned_chapters', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reader_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plot_threads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('thread_type', sa.String(length=50), nullable=True),
    sa.Column('introduced_at_chapter', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolution_chapter', sa.Integer(), nullable=True),
    sa.Column('resolution_conditions', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('related_character_ids', sa.JSON(), nullable=True),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_plot_threads_novel_status', 'plot_threads', ['novel_id', 'status'], unique=False)
    op.create_table('power_systems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('system_name', sa.String(length=200), nullable=False),
    sa.Column('core_mechanic', sa.Text(), nullable=False),
    sa.Column('energy_source', sa.Text(), nullable=False),
    sa.Column('advancement_mechanics', sa.JSON(), nullable=False),
    sa.Column('hard_limits', sa.JSON(), nullable=False),
    sa.Column('soft_limits', sa.JSON(), nullable=False),
    sa.Column('power_ceiling', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('novel_id')
    )
    op.create_table('reader_bookmarks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('last_chapter_read', sa.Integer(), nullable=False),
    sa.Column('scroll_position', sa.Float(), nullable=False),
    sa.Column('notify_on_update', sa.Boolean(), nullable=False),
    sa.Column('last_notified_chapter', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'novel_id', name='uq_reader_bookmark_user_novel')
    )
    op.create_index('idx_reader_bookmarks_notify', 'reader_bookmarks', ['novel_id', 'notify_on_update'], unique=False)
    op.create_index('idx_reader_bookmarks_user', 'reader_bookmarks', ['user_id'], unique=False)
    op.create_table('reader_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('reader_id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=True),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('intensity', sa.Integer(), nullable=False),
    sa.Column('target_entity_id', sa.Integer(), nullable=True),
    sa.Column('target_entity_type', sa.String(length=50), nullable=True),
    sa.Column('signal_data', sa.JSON(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reader_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('geography_type', sa.String(length=100), nullable=True),
    sa.Column('parent_region_id', sa.Integer(), nullable=True),
    sa.Column('climate', sa.String(length=200), nullable=True),
    sa.Column('notable_features', sa.JSON(), nullable=True),
    sa.Column('scope_tier', sa.Integer(), nullable=False),
    sa.Column('revealed_at_chapter', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_region_id'], ['regions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scope_tiers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('tier_order', sa.Integer(), nullable=False),
    sa.Column('tier_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('geography_scale', sa.Text(), nullable=True),
    sa.Column('power_range', sa.Text(), nullable=True),
    sa.Column('antagonist_caliber', sa.Text(), nullable=True),
    sa.Column('stakes_description', sa.Text(), nullable=True),
    sa.Column('key_conflicts', sa.JSON(), nullable=True),
    sa.Column('key_resources', sa.JSON(), nullable=True),
    sa.Column('revelation_triggers', sa.JSON(), nullable=True),
    sa.Column('foreshadowing_seeds_json', sa.JSON(), nullable=True),
    sa.Column('qualitative_difference', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('novel_id', 'tier_order', name='uq_scope_novel_tier')
    )
    op.create_table('story_bible_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_chapter', sa.Integer(), nullable=False),
    sa.Column('entity_ids', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('is_superseded', sa.Boolean(), nullable=False),
    sa.Column('superseded_by_id', sa.Integer(), nullable=True),
    sa.Column('is_public_knowledge', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('last_relevant_chapter', sa.Integer(), nullable=True),
    sa.Column('scope_tier', sa.Integer(), nullable=False),
    sa.Column('embedding_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['story_bible_entries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tension_tracker',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('tension_level', sa.Float(), nullable=False),
    sa.Column('tension_phase', sa.String(length=30), nullable=True),
    sa.Column('key_tension_drivers', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('novel_id', 'chapter_number', name='uq_tension_novel_chapter')
    )
    op.create_table('world_building_stages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('stage_order', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(length=50), nullable=False),
    sa.Column('prompt_used', sa.Text(), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=False),
    sa.Column('parsed_data', sa.JSON(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('novel_id', 'stage_order', name='uq_wbs_novel_stage')
    )
    op.create_table('art_generation_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('trigger_event', sa.String(length=100), nullable=True),
    sa.Column('trigger_chapter', sa.Integer(), nullable=True),
    sa.Column('source_asset_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_asset_id'], ['art_assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bible_entry_entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['story_bible_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id', 'entity_type', 'entity_id', name='uq_bible_entity_link')
    )
    op.create_table('characters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('personality_traits', sa.JSON(), nullable=True),
    sa.Column('background', sa.Text(), nullable=True),
    sa.Column('motivation', sa.Text(), nullable=True),
    sa.Column('current_goal', sa.Text(), nullable=True),
    sa.Column('faction_id', sa.Integer(), nullable=True),
    sa.Column('current_region_id', sa.Integer(), nullable=True),
    sa.Column('scope_tier', sa.Integer(), nullable=False),
    sa.Column('introduced_at_chapter', sa.Integer(), nullable=True),
    sa.Column('is_alive', sa.Boolean(), nullable=False),
    sa.Column('arc_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['current_region_id'], ['regions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['faction_id'], ['factions.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chekhov_guns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('introduced_at_chapter', sa.Integer(), nullable=False),
    sa.Column('gun_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('pressure_score', sa.Float(), nullable=False),
    sa.Column('last_touched_chapter', sa.Integer(), nullable=True),
    sa.Column('resolution_chapter', sa.Integer(), nullable=True),
    sa.Column('resolution_description', sa.Text(), nullable=True),
    sa.Column('subversion_description', sa.Text(), nullable=True),
    sa.Column('chapters_since_touch', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('bible_entry_id', sa.Integer(), nullable=True),
    sa.Column('expected_resolution_chapter', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bible_entry_id'], ['story_bible_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chekhov_novel_status', 'chekhov_guns', ['novel_id', 'status'], unique=False)
    op.create_index('idx_chekhov_pressure', 'chekhov_guns', ['novel_id', 'pressure_score'], unique=False)
    op.create_table('escalation_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('current_tier_id', sa.Integer(), nullable=False),
    sa.Column('current_phase', sa.String(length=30), nullable=False),
    sa.Column('tension_level', sa.Float(), nullable=False),
    sa.Column('relative_power', sa.Float(), nullable=False),
    sa.Column('activated_at_chapter', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['current_tier_id'], ['scope_tiers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image_usage_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('dimensions', sa.String(length=20), nullable=True),
    sa.Column('cost_cents', sa.Float(), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=True),
    sa.Column('art_asset_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['art_asset_id'], ['art_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('power_disciplines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('power_system_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('philosophy', sa.Text(), nullable=False),
    sa.Column('source_energy', sa.Text(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('weaknesses', sa.JSON(), nullable=False),
    sa.Column('typical_practitioners', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['power_system_id'], ['power_systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('power_system_id', 'name', name='uq_discipline_system_name')
    )
    op.create_table('power_ranks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('power_system_id', sa.Integer(), nullable=False),
    sa.Column('rank_name', sa.String(length=100), nullable=False),
    sa.Column('rank_order', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('typical_capabilities', sa.Text(), nullable=False),
    sa.Column('advancement_requirements', sa.Text(), nullable=False),
    sa.Column('advancement_bottleneck', sa.Text(), nullable=False),
    sa.Column('population_ratio', sa.String(length=100), nullable=True),
    sa.Column('qualitative_shift', sa.Text(), nullable=False),
    sa.Column('scope_tier', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['power_system_id'], ['power_systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('power_system_id', 'rank_order', name='uq_rank_system_order')
    )
    op.create_table('abilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('power_system_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=True),
    sa.Column('minimum_rank_id', sa.Integer(), nullable=False),
    sa.Column('energy_cost', sa.Text(), nullable=False),
    sa.Column('cooldown', sa.Text(), nullable=True),
    sa.Column('side_effects', sa.Text(), nullable=True),
    sa.Column('prerequisites', sa.JSON(), nullable=True),
    sa.Column('effects', sa.JSON(), nullable=False),
    sa.Column('mastery_levels', sa.JSON(), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('origin', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['discipline_id'], ['power_disciplines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['minimum_rank_id'], ['power_ranks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['power_system_id'], ['power_systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapter_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('arc_plan_id', sa.Integer(), nullable=True),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('scene_outline', sa.JSON(), nullable=True),
    sa.Column('target_beats', sa.JSON(), nullable=True),
    sa.Column('pov_character_id', sa.Integer(), nullable=True),
    sa.Column('target_tension', sa.Float(), nullable=True),
    sa.Column('reader_signals', sa.JSON(), nullable=True),
    sa.Column('chekhov_directives', sa.JSON(), nullable=True),
    sa.Column('plot_threads_advance', sa.JSON(), nullable=True),
    sa.Column('plot_threads_rest', sa.JSON(), nullable=True),
    sa.Column('foreshadowing_directives', sa.JSON(), nullable=True),
    sa.Column('planned_power_events', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_bridge', sa.Boolean(), nullable=False),
    sa.Column('bridge_theme', sa.String(length=100), nullable=True),
    sa.Column('author_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('NOT (is_bridge = TRUE AND arc_plan_id IS NOT NULL)', name='ck_bridge_no_arc'),
    sa.ForeignKeyConstraint(['arc_plan_id'], ['arc_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pov_character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('novel_id', 'chapter_number', name='uq_chplan_novel_chapter')
    )
    op.create_index('idx_chapter_plans_arc', 'chapter_plans', ['arc_plan_id'], unique=False)
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('arc_plan_id', sa.Integer(), nullable=True),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('chapter_text', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('pov_character_id', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('generation_params', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_bridge', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['arc_plan_id'], ['arc_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pov_character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('novel_id', 'chapter_number', name='uq_chapter_novel_number')
    )
    op.create_table('character_knowledge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('bible_entry_id', sa.Integer(), nullable=False),
    sa.Column('knows', sa.Boolean(), nullable=False),
    sa.Column('knowledge_level', sa.String(length=20), nullable=False),
    sa.Column('misconception', sa.Text(), nullable=True),
    sa.Column('learned_at_chapter', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bible_entry_id'], ['story_bible_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'bible_entry_id', name='uq_char_knowledge')
    )
    op.create_index('idx_char_knowledge_character', 'character_knowledge', ['character_id'], unique=False)
    op.create_index('idx_char_knowledge_entry', 'character_knowledge', ['bible_entry_id'], unique=False)
    op.create_table('character_power_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('current_rank_id', sa.Integer(), nullable=False),
    sa.Column('primary_discipline_id', sa.Integer(), nullable=True),
    sa.Column('secondary_discipline_id', sa.Integer(), nullable=True),
    sa.Column('advancement_progress', sa.Float(), nullable=False),
    sa.Column('energy_capacity', sa.Text(), nullable=True),
    sa.Column('bottleneck_description', sa.Text(), nullable=True),
    sa.Column('unique_traits', sa.JSON(), nullable=True),
    sa.Column('power_philosophy', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_rank_id'], ['power_ranks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['primary_discipline_id'], ['power_disciplines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['secondary_discipline_id'], ['power_disciplines.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id')
    )
    op.create_table('character_power_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('acquired_at_chapter', sa.Integer(), nullable=True),
    sa.Column('acquisition_context', sa.Text(), nullable=True),
    sa.Column('benefits', sa.JSON(), nullable=True),
    sa.Column('costs', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_relationships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_a_id', sa.Integer(), nullable=False),
    sa.Column('character_b_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('intensity', sa.Float(), nullable=False),
    sa.Column('sentiment', sa.Float(), nullable=False),
    sa.Column('established_at_chapter', sa.Integer(), nullable=False),
    sa.Column('last_interaction_chapter', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.CheckConstraint('character_a_id < character_b_id', name='ck_char_rel_ordering'),
    sa.ForeignKeyConstraint(['character_a_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_b_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_a_id', 'character_b_id', name='uq_char_rel_pair')
    )
    op.create_index('idx_char_rel_a', 'character_relationships', ['character_a_id'], unique=False)
    op.create_index('idx_char_rel_b', 'character_relationships', ['character_b_id'], unique=False)
    op.create_table('character_worldviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('core_beliefs', sa.JSON(), nullable=True),
    sa.Column('biases', sa.JSON(), nullable=True),
    sa.Column('blind_spots', sa.JSON(), nullable=True),
    sa.Column('misconceptions', sa.JSON(), nullable=True),
    sa.Column('emotional_baseline', sa.String(length=100), nullable=True),
    sa.Column('trust_disposition', sa.Text(), nullable=True),
    sa.Column('knowledge_boundaries', sa.Text(), nullable=True),
    sa.Column('updated_at_chapter', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id')
    )
    op.create_table('discipline_synergies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('discipline_a_id', sa.Integer(), nullable=False),
    sa.Column('discipline_b_id', sa.Integer(), nullable=False),
    sa.Column('synergy_description', sa.Text(), nullable=False),
    sa.Column('emergent_capability', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=100), nullable=True),
    sa.Column('known_practitioners', sa.Text(), nullable=True),
    sa.CheckConstraint('discipline_a_id < discipline_b_id', name='ck_synergy_ordering'),
    sa.ForeignKeyConstraint(['discipline_a_id'], ['power_disciplines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['discipline_b_id'], ['power_disciplines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ideology', sa.Text(), nullable=True),
    sa.Column('power_level', sa.Integer(), nullable=True),
    sa.Column('territory_region_id', sa.Integer(), nullable=True),
    sa.Column('leader_character_id', sa.Integer(), nullable=True),
    sa.Column('scope_tier', sa.Integer(), nullable=False),
    sa.Column('goals', sa.JSON(), nullable=True),
    sa.Column('resources', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['leader_character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['territory_region_id'], ['regions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('narrative_voices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('vocabulary_level', sa.String(length=30), nullable=False),
    sa.Column('speech_patterns', sa.JSON(), nullable=True),
    sa.Column('internal_monologue_style', sa.String(length=30), nullable=False),
    sa.Column('metaphor_preferences', sa.JSON(), nullable=True),
    sa.Column('emotional_expression_style', sa.String(length=100), nullable=True),
    sa.Column('sentence_style', sa.String(length=30), nullable=False),
    sa.Column('humor_style', sa.String(length=30), nullable=True),
    sa.Column('sample_passage', sa.Text(), nullable=True),
    sa.Column('voice_evolution', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id')
    )
    op.create_table('perspective_divergences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('character_a_id', sa.Integer(), nullable=False),
    sa.Column('character_b_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('character_a_belief', sa.Text(), nullable=False),
    sa.Column('character_b_belief', sa.Text(), nullable=False),
    sa.Column('ground_truth', sa.Text(), nullable=True),
    sa.Column('established_at_chapter', sa.Integer(), nullable=False),
    sa.Column('resolved_at_chapter', sa.Integer(), nullable=True),
    sa.Column('reader_has_full_picture', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['character_a_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_b_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advancement_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('struggle_context', sa.Text(), nullable=False),
    sa.Column('sacrifice_or_cost', sa.Text(), nullable=True),
    sa.Column('foundation', sa.Text(), nullable=False),
    sa.Column('narrative_buildup_chapters', sa.JSON(), nullable=True),
    sa.Column('old_rank_id', sa.Integer(), nullable=True),
    sa.Column('new_rank_id', sa.Integer(), nullable=True),
    sa.Column('ability_gained_id', sa.Integer(), nullable=True),
    sa.Column('earned_power_score', sa.Float(), nullable=True),
    sa.Column('validation_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ability_gained_id'], ['abilities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['new_rank_id'], ['power_ranks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['old_rank_id'], ['power_ranks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapter_drafts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('draft_number', sa.Integer(), nullable=False),
    sa.Column('chapter_text', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('generation_params', sa.JSON(), nullable=True),
    sa.Column('validation_result', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('retry_guidance', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('novel_id', 'chapter_number', 'draft_number', name='uq_draft_novel_chapter_draft')
    )
    op.create_index('idx_chapter_drafts_novel_chapter', 'chapter_drafts', ['novel_id', 'chapter_number'], unique=False)
    op.create_table('chapter_pov',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('pov_type', sa.String(length=30), nullable=False),
    sa.Column('worldview_snapshot', sa.JSON(), nullable=True),
    sa.Column('voice_snapshot', sa.JSON(), nullable=True),
    sa.Column('knowledge_state_snapshot', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapter_id')
    )
    op.create_table('chapter_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('summary_type', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('key_events', sa.JSON(), nullable=True),
    sa.Column('emotional_arc', sa.Text(), nullable=True),
    sa.Column('cliffhangers', sa.JSON(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapter_id', 'summary_type', name='uq_summary_chapter_type')
    )
    op.create_table('character_abilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('ability_id', sa.Integer(), nullable=False),
    sa.Column('proficiency', sa.String(length=30), nullable=False),
    sa.Column('learned_at_chapter', sa.Integer(), nullable=False),
    sa.Column('learning_method', sa.String(length=100), nullable=False),
    sa.Column('mastery_level', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'ability_id', name='uq_char_ability')
    )
    op.create_table('faction_alignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reader_id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('faction_id', sa.Integer(), nullable=False),
    sa.Column('alignment_score', sa.Float(), nullable=False),
    sa.Column('scope_tier_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['faction_id'], ['factions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reader_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scope_tier_id'], ['scope_tiers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reader_id', 'novel_id', 'faction_id', name='uq_faction_alignment')
    )
    op.create_table('faction_relationships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('faction_a_id', sa.Integer(), nullable=False),
    sa.Column('faction_b_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('intensity', sa.Float(), nullable=False),
    sa.Column('established_at_chapter', sa.Integer(), nullable=False),
    sa.Column('last_updated_chapter', sa.Integer(), nullable=True),
    sa.CheckConstraint('faction_a_id < faction_b_id', name='ck_faction_rel_ordering'),
    sa.ForeignKeyConstraint(['faction_a_id'], ['factions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faction_b_id'], ['factions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('faction_a_id', 'faction_b_id', name='uq_faction_rel_pair')
    )
    op.create_index('idx_faction_rel_a', 'faction_relationships', ['faction_a_id'], unique=False)
    op.create_index('idx_faction_rel_b', 'faction_relationships', ['faction_b_id'], unique=False)
    op.create_table('historical_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('era', sa.String(length=200), nullable=True),
    sa.Column('chronological_order', sa.Integer(), nullable=True),
    sa.Column('impact', sa.JSON(), nullable=True),
    sa.Column('related_region_id', sa.Integer(), nullable=True),
    sa.Column('related_faction_id', sa.Integer(), nullable=True),
    sa.Column('is_common_knowledge', sa.Boolean(), nullable=False),
    sa.Column('scope_tier', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_faction_id'], ['factions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_region_id'], ['regions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historical_events')
    op.drop_index('idx_faction_rel_b', table_name='faction_relationships')
    op.drop_index('idx_faction_rel_a', table_name='faction_relationships')
    op.drop_table('faction_relationships')
    op.drop_table('faction_alignments')
    op.drop_table('character_abilities')
    op.drop_table('chapter_summaries')
    op.drop_table('chapter_pov')
    op.drop_index('idx_chapter_drafts_novel_chapter', table_name='chapter_drafts')
    op.drop_table('chapter_drafts')
    op.drop_table('advancement_events')
    op.drop_table('perspective_divergences')
    op.drop_table('narrative_voices')
    op.drop_table('factions')
    op.drop_table('discipline_synergies')
    op.drop_table('character_worldviews')
    op.drop_index('idx_char_rel_b', table_name='character_relationships')
    op.drop_index('idx_char_rel_a', table_name='character_relationships')
    op.drop_table('character_relationships')
    op.drop_table('character_power_sources')
    op.drop_table('character_power_profiles')
    op.drop_index('idx_char_knowledge_entry', table_name='character_knowledge')
    op.drop_index('idx_char_knowledge_character', table_name='character_knowledge')
    op.drop_table('character_knowledge')
    op.drop_table('chapters')
    op.drop_index('idx_chapter_plans_arc', table_name='chapter_plans')
    op.drop_table('chapter_plans')
    op.drop_table('abilities')
    op.drop_table('power_ranks')
    op.drop_table('power_disciplines')
    op.drop_table('image_usage_log')
    op.drop_table('escalation_state')
    op.drop_index('idx_chekhov_pressure', table_name='chekhov_guns')
    op.drop_index('idx_chekhov_novel_status', table_name='chekhov_guns')
    op.drop_table('chekhov_guns')
    op.drop_table('characters')
    op.drop_table('bible_entry_entities')
    op.drop_table('art_generation_queue')
    op.drop_table('world_building_stages')
    op.drop_table('tension_tracker')
    op.drop_table('story_bible_entries')
    op.drop_table('scope_tiers')
    op.drop_table('regions')
    op.drop_table('reader_signals')
    op.drop_index('idx_reader_bookmarks_user', table_name='reader_bookmarks')
    op.drop_index('idx_reader_bookmarks_notify', table_name='reader_bookmarks')
    op.drop_table('reader_bookmarks')
    op.drop_table('power_systems')
    op.drop_index('idx_plot_threads_novel_status', table_name='plot_threads')
    op.drop_table('plot_threads')
    op.drop_table('oracle_questions')
    op.drop_table('novel_tags')
    op.drop_table('novel_stats')
    op.drop_table('novel_settings')
    op.drop_table('novel_ratings')
    op.drop_table('novel_access')
    op.drop_index('idx_notifications_user_unread', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_llm_usage_user', table_name='llm_usage_log')
    op.drop_index('idx_llm_usage_novel', table_name='llm_usage_log')
    op.drop_index('idx_llm_usage_created', table_name='llm_usage_log')
    op.drop_table('llm_usage_log')
    op.drop_index('idx_generation_jobs_status', table_name='generation_jobs')
    op.drop_index('idx_generation_jobs_novel', table_name='generation_jobs')
    op.drop_table('generation_jobs')
    op.drop_table('foreshadowing_seeds')
    op.drop_table('cosmology')
    op.drop_table('context_retrieval_log')
    op.drop_table('butterfly_choices')
    op.drop_table('art_style_guides')
    op.drop_table('art_assets')
    op.drop_index('idx_arc_plans_novel_status', table_name='arc_plans')
    op.drop_table('arc_plans')
    op.drop_table('reader_profiles')
    op.drop_index('idx_novels_author', table_name='novels')
    op.drop_table('novels')
    op.drop_table('author_profiles')
    op.drop_index('idx_users_email', table_name='users', postgresql_where='email IS NOT NULL')
    op.drop_index('idx_users_cookie_token', table_name='users', postgresql_where='cookie_token IS NOT NULL')
    op.drop_table('users')
    # ### end Alembic commands ###
